### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by flyfishMT** [lucasbasquerotto/react-masked-input#1]
Do you plan to support React 18? And continue to support React 17? I see that you specifically require 17.0.2 as a peerDependency. Thanks

**Comment by meridPL** [comment]
Try something like this:
`npm config set legacy-peer-deps true`

**Comment by lucasbasquerotto** [comment]
From the react blog post (https://reactjs.org/blog/2020/10/20/react-v17.html), it seems that moving forward older versions of react should "just work" when included in applications with newer versions (theoretically).

To make it easier for the library users, I changed the `peerDependencies` to allow all newer react versions from 17.0.0 onwards.

I tested with react 18 and it worked.

You can try the new released version 1.1.11 (https://www.npmjs.com/package/react-hook-mask)

Thanks for opening the issue. I will close it because it seems to be resolved. You can reopen it or open a new issue otherwise.
